version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: moodle_llm
      POSTGRES_USER: moodle_user
      POSTGRES_PASSWORD: moodle_pass
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://moodle_user:moodle_pass@db:5432/moodle_llm
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/downloads:/app/downloads
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  worker:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - ./backend/downloads:/app/downloads
    depends_on:
      - db
      - redis
    command: celery -A celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DATABASE_URL=postgresql://moodle_user:moodle_pass@db:5432/moodle_llm
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    stdin_open: true
    tty: true
volumes:
  pgdata:
  frontend_node_modules:
