version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: moodle_llm
      POSTGRES_USER: moodle_user
      POSTGRES_PASSWORD: moodle_pass
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://moodle_user:moodle_pass@db:5432/moodle_llm
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    stdin_open: true
    tty: true
volumes:
  pgdata:
  frontend_node_modules:
